[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "langextract-clients"
version = "0.1.0"
description = "Python SDK for LangExtract API"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = ["langextract"]

